// Complete Labubu Dataset - All 113 Figures
// Updated with new JSON data structure including description field
// Preserves existing image and color fields
// NOTE: storeLink is handled separately by the Store screen
export const LABUBU_DATA = [
    // Exciting Macaron Series (7 figures: 6 common, 1 secret)
    {
        id: '1',
        name: 'Lychee Berry',
        series: 'Exciting Macaron',
        releaseDate: '2023-10-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=Lychee+Berry',
        rarity: 'Common',
        color: 'Pink',
        estimatedValue: { min: 45, max: 45 },
        originalPrice: 12.9,
        description: 'Pink macaron flavor',
    },
    {
        id: '2',
        name: 'Sesame Bean',
        series: 'Exciting Macaron',
        releaseDate: '2023-10-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/696969/FFFFFF?text=Sesame+Bean',
        rarity: 'Common',
        color: 'Grey',
        estimatedValue: { min: 40, max: 40 },
        originalPrice: 12.9,
        description: 'Black sesame flavor',
    },
    {
        id: '3',
        name: 'Green Grape',
        series: 'Exciting Macaron',
        releaseDate: '2023-10-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/32CD32/FFFFFF?text=Green+Grape',
        rarity: 'Common',
        color: 'Green',
        estimatedValue: { min: 38, max: 38 },
        originalPrice: 12.9,
        description: 'Green grape flavor',
    },
    {
        id: '4',
        name: 'Soy Milk',
        series: 'Exciting Macaron',
        releaseDate: '2023-10-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/F5F5DC/FFFFFF?text=Soy+Milk',
        rarity: 'Common',
        color: 'Cream',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 12.9,
        description: 'Soy milk flavor',
    },
    {
        id: '5',
        name: 'Sea Salt Coconut',
        series: 'Exciting Macaron',
        releaseDate: '2023-10-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/87CEEB/FFFFFF?text=Sea+Salt',
        rarity: 'Common',
        color: 'Blue',
        estimatedValue: { min: 42, max: 42 },
        originalPrice: 12.9,
        description: 'Sea salt coconut flavor',
    },
    {
        id: '6',
        name: 'Toffee',
        series: 'Exciting Macaron',
        releaseDate: '2023-10-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/D2691E/FFFFFF?text=Toffee',
        rarity: 'Common',
        color: 'Brown',
        estimatedValue: { min: 38, max: 38 },
        originalPrice: 12.9,
        description: 'Toffee flavor',
    },
    {
        id: '7',
        name: 'Chestnut Cocoa (Secret)',
        series: 'Exciting Macaron',
        releaseDate: '2023-10-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/8B4513/FFFFFF?text=Secret',
        rarity: 'Secret',
        color: 'Dark Brown',
        estimatedValue: { min: 120, max: 120 },
        originalPrice: 12.9,
        description: 'Chestnut cocoa secret',
    },

    // Have a Seat Series (7 figures: 6 common, 1 secret)
    {
        id: '8',
        name: 'Sisi',
        series: 'Have a Seat',
        releaseDate: '2023-09-15',
        dimensions: '8cm / 3.2 inches',
        image: 'https://via.placeholder.com/150/F5DEB3/FFFFFF?text=Sisi',
        rarity: 'Common',
        color: 'Light Beige',
        estimatedValue: { min: 35, max: 35 },
        originalPrice: 13.5,
        description: 'Beige calm expression',
    },
    {
        id: '9',
        name: 'Hehe',
        series: 'Have a Seat',
        releaseDate: '2023-09-15',
        dimensions: '8cm / 3.2 inches',
        image: 'https://via.placeholder.com/150/808080/FFFFFF?text=Hehe',
        rarity: 'Common',
        color: 'Gray',
        estimatedValue: { min: 32, max: 32 },
        originalPrice: 13.5,
        description: 'Gray cheeky grin',
    },
    {
        id: '10',
        name: 'Zizi',
        series: 'Have a Seat',
        releaseDate: '2023-09-15',
        dimensions: '8cm / 3.2 inches',
        image: 'https://via.placeholder.com/150/FFB6C1/FFFFFF?text=Zizi',
        rarity: 'Common',
        color: 'Pink',
        estimatedValue: { min: 30, max: 30 },
        originalPrice: 13.5,
        description: 'Playful expression',
    },
    {
        id: '11',
        name: 'Baba',
        series: 'Have a Seat',
        releaseDate: '2023-09-15',
        dimensions: '8cm / 3.2 inches',
        image: 'https://via.placeholder.com/150/98FB98/FFFFFF?text=Baba',
        rarity: 'Common',
        color: 'Green',
        estimatedValue: { min: 28, max: 28 },
        originalPrice: 13.5,
        description: 'Relaxed pose',
    },
    {
        id: '12',
        name: 'Ququ',
        series: 'Have a Seat',
        releaseDate: '2023-09-15',
        dimensions: '8cm / 3.2 inches',
        image: 'https://via.placeholder.com/150/00FF7F/FFFFFF?text=Ququ',
        rarity: 'Common',
        color: 'Mint Green',
        estimatedValue: { min: 35, max: 35 },
        originalPrice: 13.5,
        description: 'Mint green excited eyes',
    },
    {
        id: '13',
        name: 'Dada',
        series: 'Have a Seat',
        releaseDate: '2023-09-15',
        dimensions: '8cm / 3.2 inches',
        image: 'https://via.placeholder.com/150/FFB6C1/FFFFFF?text=Dada',
        rarity: 'Common',
        color: 'Pale Pink',
        estimatedValue: { min: 32, max: 32 },
        originalPrice: 13.5,
        description: 'Pale pink sparkling eyes',
    },
    {
        id: '14',
        name: 'DuoDuo (Secret)',
        series: 'Have a Seat',
        releaseDate: '2023-09-15',
        dimensions: '8cm / 3.2 inches',
        image: 'https://via.placeholder.com/150/8B4513/FFFFFF?text=Secret',
        rarity: 'Secret',
        color: 'Chocolate Brown',
        estimatedValue: { min: 150, max: 150 },
        originalPrice: 13.5,
        description: 'Chocolate brown secret',
    },

    // Big into Energy Series (7 figures: 6 common, 1 secret)
    {
        id: '15',
        name: 'Love',
        series: 'Big into Energy',
        releaseDate: '2025-04-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Hope',
        rarity: 'Common',
        color: 'Yellow',
        estimatedValue: { min: 25, max: 25 },
        originalPrice: 14,
        description: 'Red emotion variant',
    },
    {
        id: '16',
        name: 'Happiness',
        series: 'Big into Energy',
        releaseDate: '2025-04-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/FF4500/FFFFFF?text=Power',
        rarity: 'Common',
        color: 'Orange',
        estimatedValue: { min: 28, max: 28 },
        originalPrice: 14,
        description: 'Orange emotion variant',
    },
    {
        id: '17',
        name: 'Loyalty',
        series: 'Big into Energy',
        releaseDate: '2025-04-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/00FF00/FFFFFF?text=Energy',
        rarity: 'Common',
        color: 'Green',
        estimatedValue: { min: 30, max: 30 },
        originalPrice: 14,
        description: 'Pink/yellow tie-dye',
    },
    {
        id: '18',
        name: 'Serenity',
        series: 'Big into Energy',
        releaseDate: '2025-04-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/FF0000/FFFFFF?text=Adrenaline',
        rarity: 'Common',
        color: 'Red',
        estimatedValue: { min: 26, max: 26 },
        originalPrice: 14,
        description: 'Green emotion variant',
    },
    {
        id: '19',
        name: 'Hope',
        series: 'Big into Energy',
        releaseDate: '2025-04-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/0000FF/FFFFFF?text=Boost',
        rarity: 'Common',
        color: 'Blue',
        estimatedValue: { min: 27, max: 27 },
        originalPrice: 14,
        description: 'Blue emotion variant',
    },
    {
        id: '20',
        name: 'Luck',
        series: 'Big into Energy',
        releaseDate: '2025-04-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/800080/FFFFFF?text=Charge',
        rarity: 'Common',
        color: 'Purple',
        estimatedValue: { min: 35, max: 35 },
        originalPrice: 14,
        description: 'Purple emotion variant',
    },
    {
        id: '21',
        name: 'Super Energy (Secret)',
        series: 'Big into Energy',
        releaseDate: '2025-04-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/FF1493/FFFFFF?text=Secret',
        rarity: 'Secret',
        color: 'Cosmic',
        estimatedValue: { min: 250, max: 250 },
        originalPrice: 14,
        description: 'Rainbow glitter secret (Rock the Universe)',
    },

    // Pin for Love Series (30 figures: 28 common, 2 secret)
    {
        id: '22',
        name: 'A - Adventure',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=A',
        rarity: 'Common',
        color: 'Pink',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter A pendant',
    },
    {
        id: '23',
        name: 'B - Belief',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/32CD32/FFFFFF?text=B',
        rarity: 'Common',
        color: 'Green',
        estimatedValue: { min: 11.5, max: 11.5 },
        originalPrice: 10.5,
        description: 'Letter B pendant',
    },
    {
        id: '24',
        name: 'C - Courage',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=C%20-%20Courage',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter C pendant',
    },
    {
        id: '25',
        name: 'D - Dream',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=D%20-%20Dream',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter D pendant',
    },
    {
        id: '26',
        name: 'E - Excitement',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=E%20-%20Excitement',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter E pendant',
    },
    {
        id: '27',
        name: 'F - Faith',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=F%20-%20Faith',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter F pendant',
    },
    {
        id: '28',
        name: 'G - Gratitude',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=G%20-%20Gratitude',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter G pendant',
    },
    {
        id: '29',
        name: 'H - Hope',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=H%20-%20Hope',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter H pendant',
    },
    {
        id: '30',
        name: 'I - Inspiration',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=I%20-%20Inspiration',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter I pendant',
    },
    {
        id: '31',
        name: 'J - Joy',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=J%20-%20Joy',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter J pendant',
    },
    {
        id: '32',
        name: 'K - Kindness',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=K%20-%20Kindness',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter K pendant',
    },
    {
        id: '33',
        name: 'L - Love',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=L%20-%20Love',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 15, max: 15 },
        originalPrice: 10.5,
        description: 'Letter L pendant',
    },
    {
        id: '34',
        name: 'M - Magic',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=M%20-%20Magic',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter M pendant',
    },
    {
        id: '35',
        name: 'N - Nature',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=N%20-%20Nature',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter N pendant',
    },
    {
        id: '36',
        name: 'O - Optimism',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=O%20-%20Optimism',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter O pendant',
    },
    {
        id: '37',
        name: 'P - Passion',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=P%20-%20Passion',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter P pendant',
    },
    {
        id: '38',
        name: 'Q - Quiet',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=Q%20-%20Quiet',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter Q pendant',
    },
    {
        id: '39',
        name: 'R - Resilience',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=R%20-%20Resilience',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter R pendant',
    },
    {
        id: '40',
        name: 'S - Strength',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=S%20-%20Strength',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter S pendant',
    },
    {
        id: '41',
        name: 'T - Trust',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=T%20-%20Trust',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter T pendant',
    },
    {
        id: '42',
        name: 'U - Unity',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=U%20-%20Unity',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter U pendant',
    },
    {
        id: '43',
        name: 'V - Victory',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=V%20-%20Victory',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter V pendant',
    },
    {
        id: '44',
        name: 'W - Wisdom',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=W%20-%20Wisdom',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter W pendant',
    },
    {
        id: '45',
        name: 'X - Xtra',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=X%20-%20Xtra',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 15, max: 15 },
        originalPrice: 10.5,
        description: 'Letter X pendant',
    },
    {
        id: '46',
        name: 'Y - Youth',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=Y%20-%20Youth',
        rarity: 'Common',
        color: 'Unknown',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter Y pendant',
    },
    {
        id: '47',
        name: 'Z - Zeal',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/9370DB/FFFFFF?text=Z',
        rarity: 'Common',
        color: 'Medium Purple',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.5,
        description: 'Letter Z pendant',
    },
    {
        id: '48',
        name: '? - Emm',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/800080/FFFFFF?text=?',
        rarity: 'Common',
        color: 'Purple',
        estimatedValue: { min: 20, max: 20 },
        originalPrice: 10.5,
        description: 'Purple question mark',
    },
    {
        id: '49',
        name: '&',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=&',
        rarity: 'Common',
        color: 'Hot Pink',
        estimatedValue: { min: 18, max: 18 },
        originalPrice: 10.5,
        description: 'Ampersand symbol',
    },
    {
        id: '50',
        name: 'Heart (Secret)',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF1493/FFFFFF?text=Heart',
        rarity: 'Secret',
        color: 'Deep Pink',
        estimatedValue: { min: 80, max: 80 },
        originalPrice: 10.5,
        description: 'Heart secret',
    },
    {
        id: '51',
        name: '! (Secret)',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=!',
        rarity: 'Secret',
        color: 'Gold',
        estimatedValue: { min: 90, max: 90 },
        originalPrice: 10.5,
        description: 'Exclamation secret',
    },

    // Coca-Cola Series (12 figures: 10 common, 2 secret)
    {
        id: '52',
        name: 'Classic Coke',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/C0C0C0/FFFFFF?text=Coke',
        rarity: 'Common',
        color: 'Silver',
        estimatedValue: { min: 18, max: 18 },
        originalPrice: 15,
        description: 'Classic red can design',
    },
    {
        id: '53',
        name: 'Coke Bottle',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/8B4513/FFFFFF?text=Bottle',
        rarity: 'Common',
        color: 'Brown',
        estimatedValue: { min: 17, max: 17 },
        originalPrice: 15,
        description: 'Glass bottle shape',
    },
    {
        id: '54',
        name: 'Cherry Coke',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/FF0000/FFFFFF?text=Cherry',
        rarity: 'Common',
        color: 'Red',
        estimatedValue: { min: 19, max: 19 },
        originalPrice: 15,
        description: 'Cherry flavor variant',
    },
    {
        id: '55',
        name: 'Diet Coke',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/708090/FFFFFF?text=Diet',
        rarity: 'Common',
        color: 'Slate Gray',
        estimatedValue: { min: 17, max: 17 },
        originalPrice: 15,
        description: 'Silver can design',
    },
    {
        id: '56',
        name: 'Coke Zero',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/000000/FFFFFF?text=Zero',
        rarity: 'Common',
        color: 'Black',
        estimatedValue: { min: 18, max: 18 },
        originalPrice: 15,
        description: 'Black can design',
    },
    {
        id: '57',
        name: 'Vanilla Coke',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/F5DEB3/FFFFFF?text=Vanilla',
        rarity: 'Common',
        color: 'Wheat',
        estimatedValue: { min: 20, max: 20 },
        originalPrice: 15,
        description: 'Cream vanilla variant',
    },
    {
        id: '58',
        name: 'Surfboard Coke',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/87CEEB/FFFFFF?text=Surf',
        rarity: 'Common',
        color: 'Sky Blue',
        estimatedValue: { min: 22, max: 22 },
        originalPrice: 15,
        description: 'Beach surfboard design',
    },
    {
        id: '59',
        name: 'Festive Coke',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Festive',
        rarity: 'Common',
        color: 'Gold',
        estimatedValue: { min: 18, max: 18 },
        originalPrice: 15,
        description: 'Holiday theme',
    },
    {
        id: '60',
        name: 'Polar Bear Coke (Secret)',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/C0C0C0/FFFFFF?text=Silver',
        rarity: 'Secret',
        color: 'Silver',
        estimatedValue: { min: 200, max: 200 },
        originalPrice: 15,
        description: 'Polar bear secret',
    },
    {
        id: '111',
        name: 'Holiday Coke Labubu',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/87CEEB/FFFFFF?text=Starry+Adventure',
        rarity: 'Common',
        color: 'Sky Blue',
        estimatedValue: { min: 18, max: 18 },
        originalPrice: 15,
        description: 'Festive red & white',
    },
    {
        id: '112',
        name: 'Silver Can Labubu',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/32CD32/FFFFFF?text=Lucky+Clover',
        rarity: 'Rare',
        color: 'Lime Green',
        estimatedValue: { min: 35, max: 35 },
        originalPrice: 15,
        description: 'Shiny silver variant',
    },
    {
        id: '113',
        name: 'Coke Secret Variant',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Mega+Edition',
        rarity: 'Secret',
        color: 'Gold',
        estimatedValue: { min: 150, max: 150 },
        originalPrice: 15,
        description: 'Special secret',
    },

    // Standalone Plush Series (25 figures: 25 common)
    {
        id: '61',
        name: 'Time to Chill Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-02-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/8B0000/FFFFFF?text=Secret',
        rarity: 'Limited',
        color: 'Dark Red',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99,
        description: 'Sunglasses relaxed pose',
    },
    {
        id: '62',
        name: 'Jump for Joy Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-04-10',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FF0000/FFFFFF?text=Holiday',
        rarity: 'Limited',
        color: 'Red',
        estimatedValue: { min: 45, max: 45 },
        originalPrice: 39.99,
        description: 'Bouncing pose',
    },
    {
        id: '63',
        name: 'Dress Be Latte Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-06-20',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/228B22/FFFFFF?text=Big+Wild',
        rarity: 'Limited',
        color: 'Forest Green',
        estimatedValue: { min: 48, max: 48 },
        originalPrice: 39.99,
        description: 'Coffee outfit',
    },
    {
        id: '64',
        name: 'Flip with Me Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-08-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/32CD32/FFFFFF?text=Wild+Key',
        rarity: 'Limited',
        color: 'Lime Green',
        estimatedValue: { min: 47, max: 47 },
        originalPrice: 39.99,
        description: 'Acrobatic pose',
    },
    {
        id: '65',
        name: 'Let\'s Checkmate Labubu (Big)',
        series: 'Standalone Plush',
        releaseDate: '2024-09-10',
        dimensions: '30cm / 11.8 inches',
        image: 'https://via.placeholder.com/150/87CEEB/FFFFFF?text=Chill',
        rarity: 'Limited',
        color: 'Sky Blue',
        estimatedValue: { min: 60, max: 60 },
        originalPrice: 49.99,
        description: 'Chess king design',
    },
    {
        id: '66',
        name: 'Walk By Fortune Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-10-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Joy',
        rarity: 'Limited',
        color: 'Gold',
        estimatedValue: { min: 55, max: 55 },
        originalPrice: 39.99,
        description: 'Lucky cat theme',
    },
    {
        id: '67',
        name: 'Best of Luck Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-10-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/D2691E/FFFFFF?text=Latte',
        rarity: 'Limited',
        color: 'Chocolate',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99,
        description: 'Fortune theme',
    },
    {
        id: '68',
        name: 'Catch Me If You Like Me Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-07-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=Flip',
        rarity: 'Limited',
        color: 'Hot Pink',
        estimatedValue: { min: 45, max: 45 },
        originalPrice: 39.99,
        description: 'Playful chase',
    },
    {
        id: '69',
        name: 'Be Fancy Now Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-11-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/696969/FFFFFF?text=Chess+Big',
        rarity: 'Limited',
        color: 'Dim Gray',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99,
        description: 'Glam outfit',
    },
    {
        id: '70',
        name: 'Wings of Fantasy Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-12-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/808080/FFFFFF?text=Chess+Key',
        rarity: 'Limited',
        color: 'Gray',
        estimatedValue: { min: 52, max: 52 },
        originalPrice: 39.99,
        description: 'Fairy wings',
    },
    {
        id: '79',
        name: 'Forest Fairy Tale Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-08-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=Hide+Seek',
        rarity: 'Limited',
        color: 'Hot Pink',
        estimatedValue: { min: 48, max: 48 },
        originalPrice: 39.99,
        description: 'Enchanted forest',
    },
    {
        id: '80',
        name: 'Space Adventure Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-10-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Good+Lucky',
        rarity: 'Limited',
        color: 'Gold',
        estimatedValue: { min: 52, max: 52 },
        originalPrice: 39.99,
        description: 'Astronaut Labubu',
    },
    {
        id: '81',
        name: 'Playing Games Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-11-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/4B0082/FFFFFF?text=Universe',
        rarity: 'Limited',
        color: 'Indigo',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99,
        description: 'Gamer Labubu',
    },
    {
        id: '84',
        name: 'Mermaid Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-07-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=Sweet+Key',
        rarity: 'Limited',
        color: 'Hot Pink',
        estimatedValue: { min: 55, max: 55 },
        originalPrice: 39.99,
        description: 'Ocean mermaid',
    },
    {
        id: '87',
        name: 'Candy Carnival Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-10-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/4169E1/FFFFFF?text=Diamond',
        rarity: 'Limited',
        color: 'Royal Blue',
        estimatedValue: { min: 52, max: 52 },
        originalPrice: 39.99,
        description: 'Candy theme',
    },
    {
        id: '91',
        name: 'Wacky Mart Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-09-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/87CEEB/FFFFFF?text=Angel+Clouds',
        rarity: 'Limited',
        color: 'Sky Blue',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99,
        description: 'Pop Mart store theme',
    },
    {
        id: '92',
        name: 'Starry Adventure Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-09-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFB6C1/FFFFFF?text=Boyfriend',
        rarity: 'Limited',
        color: 'Light Pink',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99,
        description: 'Star theme',
    },
    {
        id: '94',
        name: 'Tropical Paradise Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-07-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Wacky+Mart',
        rarity: 'Limited',
        color: 'Gold',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99,
        description: 'Island theme',
    },
    {
        id: '95',
        name: 'Moonlit Garden Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-08-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/4169E1/FFFFFF?text=Space+Adventure',
        rarity: 'Limited',
        color: 'Royal Blue',
        estimatedValue: { min: 48, max: 48 },
        originalPrice: 39.99,
        description: 'Night garden',
    },
    {
        id: '97',
        name: 'Rainbow Dream Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-09-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/F0F8FF/FFFFFF?text=Snowflake',
        rarity: 'Limited',
        color: 'Alice Blue',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99,
        description: 'Rainbow colors',
    },
    {
        id: '99',
        name: 'Cosmic Explorer Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-10-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Lunar+New+Year',
        rarity: 'Limited',
        color: 'Gold',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99,
        description: 'Space explorer',
    },
    {
        id: '100',
        name: 'Dreamy Cloud Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-11-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/00CED1/FFFFFF?text=Mermaid',
        rarity: 'Limited',
        color: 'Dark Turquoise',
        estimatedValue: { min: 48, max: 48 },
        originalPrice: 39.99,
        description: 'Fluffy cloud',
    },
    {
        id: '106',
        name: 'Let\'s Checkmate Hangcard',
        series: 'Standalone Plush',
        releaseDate: '2024-09-10',
        dimensions: '10cm / 3.9 inches',
        image: 'https://via.placeholder.com/150/4B0082/FFFFFF?text=Cosmic+Explorer',
        rarity: 'Limited',
        color: 'Indigo',
        estimatedValue: { min: 25, max: 25 },
        originalPrice: 19.99,
        description: 'Chess keychain',
    },
    {
        id: '107',
        name: 'Wings of Fortune Labubu',
        series: 'Standalone Plush',
        releaseDate: '2024-12-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/F0F8FF/FFFFFF?text=Dreamy+Cloud',
        rarity: 'Limited',
        color: 'Alice Blue',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99,
        description: 'Golden wings',
    },
    {
        id: '110',
        name: 'Rock the Universe Labubu (30cm)',
        series: 'Standalone Plush',
        releaseDate: '2024-11-15',
        dimensions: '30cm / 11.8 inches',
        image: 'https://via.placeholder.com/150/9370DB/FFFFFF?text=Moonlit+Garden',
        rarity: 'Limited',
        color: 'Medium Purple',
        estimatedValue: { min: 65, max: 65 },
        originalPrice: 49.99,
        description: 'Cosmic large plush',
    },

    // Regional Exclusive Series (3 figures: 3 common)
    {
        id: '71',
        name: 'Hide and Seek Singapore Labubu',
        series: 'Regional Exclusive',
        releaseDate: '2024-06-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Fortune',
        rarity: 'Limited',
        color: 'Gold',
        estimatedValue: { min: 80, max: 80 },
        originalPrice: 45,
        description: 'Singapore exclusive',
    },
    {
        id: '72',
        name: 'Good Lucky Thailand Labubu',
        series: 'Regional Exclusive',
        releaseDate: '2024-06-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/32CD32/FFFFFF?text=Luck',
        rarity: 'Limited',
        color: 'Lime Green',
        estimatedValue: { min: 75, max: 75 },
        originalPrice: 45,
        description: 'Thailand exclusive',
    },
    {
        id: '82',
        name: 'Sakura Blossom Labubu',
        series: 'Regional Exclusive',
        releaseDate: '2024-03-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Anniversary',
        rarity: 'Limited',
        color: 'Gold',
        estimatedValue: { min: 70, max: 70 },
        originalPrice: 45,
        description: 'Japan cherry blossom',
    },

    // Anniversary Series (1 figures: 1 common)
    {
        id: '73',
        name: '14th Anniversary Labubu',
        series: 'Anniversary',
        releaseDate: '2024-12-10',
        dimensions: '30cm / 11.8 inches',
        image: 'https://via.placeholder.com/150/FF1493/FFFFFF?text=Catch+Me',
        rarity: 'Limited',
        color: 'Deep Pink',
        estimatedValue: { min: 90, max: 90 },
        originalPrice: 59.99,
        description: 'Pop Mart 14th anniversary edition',
    },

    // Mokoko Series (7 figures: 7 common)
    {
        id: '74',
        name: 'Close to Sweet Mokoko (Big)',
        series: 'Mokoko',
        releaseDate: '2024-03-15',
        dimensions: '30cm / 11.8 inches',
        image: 'https://via.placeholder.com/150/000000/FFFFFF?text=Vans',
        rarity: 'Limited',
        color: 'Black',
        estimatedValue: { min: 60, max: 60 },
        originalPrice: 49.99,
        description: 'Large sweet Mokoko',
    },
    {
        id: '75',
        name: 'Fall into Spring Mokoko (Big)',
        series: 'Mokoko',
        releaseDate: '2024-04-01',
        dimensions: '30cm / 11.8 inches',
        image: 'https://via.placeholder.com/150/FF8C00/FFFFFF?text=Pumpkin',
        rarity: 'Limited',
        color: 'Dark Orange',
        estimatedValue: { min: 58, max: 58 },
        originalPrice: 49.99,
        description: 'Floral Mokoko',
    },
    {
        id: '76',
        name: 'The Blue Diamond Mokoko',
        series: 'Mokoko',
        releaseDate: '2024-05-10',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/9370DB/FFFFFF?text=Fancy',
        rarity: 'Limited',
        color: 'Medium Purple',
        estimatedValue: { min: 70, max: 70 },
        originalPrice: 39.99,
        description: 'Blue sparkling Mokoko',
    },
    {
        id: '102',
        name: 'Magic of Pumpkin Mokoko',
        series: 'Mokoko',
        releaseDate: '2024-10-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=Rainbow+Dream',
        rarity: 'Limited',
        color: 'Hot Pink',
        estimatedValue: { min: 65, max: 65 },
        originalPrice: 39.99,
        description: 'Halloween pumpkin Mokoko',
    },
    {
        id: '103',
        name: 'Twinkly Fairy Tale Mokoko',
        series: 'Mokoko',
        releaseDate: '2024-12-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Candy+Carnival',
        rarity: 'Limited',
        color: 'Gold',
        estimatedValue: { min: 52, max: 52 },
        originalPrice: 39.99,
        description: 'Fairy tale Mokoko',
    },
    {
        id: '108',
        name: 'Close to Sweet Keychain',
        series: 'Mokoko',
        releaseDate: '2024-03-15',
        dimensions: '10cm / 3.9 inches',
        image: 'https://via.placeholder.com/150/FF4500/FFFFFF?text=Festival+Fireworks',
        rarity: 'Limited',
        color: 'Orange Red',
        estimatedValue: { min: 25, max: 25 },
        originalPrice: 19.99,
        description: 'Mini sweet Mokoko',
    },
    {
        id: '109',
        name: 'Fall into Spring Keychain',
        series: 'Mokoko',
        releaseDate: '2024-04-01',
        dimensions: '10cm / 3.9 inches',
        image: 'https://via.placeholder.com/150/32CD32/FFFFFF?text=Tropical+Paradise',
        rarity: 'Limited',
        color: 'Lime Green',
        estimatedValue: { min: 24, max: 24 },
        originalPrice: 19.99,
        description: 'Mini floral Mokoko',
    },

    // Zimomo Series (2 figures: 2 common)
    {
        id: '77',
        name: 'I Found You Zimomo',
        series: 'Zimomo',
        releaseDate: '2024-06-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/DDA0DD/FFFFFF?text=Fantasy',
        rarity: 'Limited',
        color: 'Plum',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99,
        description: 'Hide-and-seek Zimomo',
    },
    {
        id: '78',
        name: 'Angel in Clouds Zimomo',
        series: 'Zimomo',
        releaseDate: '2024-06-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Fortune+Wings',
        rarity: 'Rare',
        color: 'Gold',
        estimatedValue: { min: 65, max: 65 },
        originalPrice: 39.99,
        description: 'Cloud angel Zimomo',
    },

    // Holiday Series (7 figures: 7 common)
    {
        id: '83',
        name: 'Lunar New Year Labubu',
        series: 'Holiday',
        releaseDate: '2025-01-28',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFB6C1/FFFFFF?text=Sweet+Big',
        rarity: 'Limited',
        color: 'Light Pink',
        estimatedValue: { min: 65, max: 65 },
        originalPrice: 45,
        description: 'Red & gold festive',
    },
    {
        id: '85',
        name: 'Halloween Pumpkin Labubu',
        series: 'Holiday',
        releaseDate: '2024-10-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/98FB98/FFFFFF?text=Spring+Big',
        rarity: 'Limited',
        color: 'Pale Green',
        estimatedValue: { min: 60, max: 60 },
        originalPrice: 39.99,
        description: 'Sitting pumpkin',
    },
    {
        id: '86',
        name: 'Winter Snowflake Labubu',
        series: 'Holiday',
        releaseDate: '2024-12-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/32CD32/FFFFFF?text=Spring+Key',
        rarity: 'Limited',
        color: 'Lime Green',
        estimatedValue: { min: 55, max: 55 },
        originalPrice: 39.99,
        description: 'Snowflake design',
    },
    {
        id: '88',
        name: 'Golden Harvest Labubu',
        series: 'Holiday',
        releaseDate: '2024-11-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FF8C00/FFFFFF?text=Magic+Pumpkin',
        rarity: 'Limited',
        color: 'Dark Orange',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99,
        description: 'Autumn gold',
    },
    {
        id: '93',
        name: 'Lucky Clover Labubu',
        series: 'Holiday',
        releaseDate: '2024-10-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/228B22/FFFFFF?text=Forest+Fairy',
        rarity: 'Limited',
        color: 'Forest Green',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99,
        description: 'Four-leaf clover',
    },
    {
        id: '96',
        name: 'Festival Fireworks Labubu',
        series: 'Holiday',
        releaseDate: '2024-12-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/9370DB/FFFFFF?text=Playing+Games',
        rarity: 'Limited',
        color: 'Medium Purple',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99,
        description: 'Fireworks theme',
    },
    {
        id: '98',
        name: 'Frosty Winter Labubu',
        series: 'Holiday',
        releaseDate: '2024-12-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFB6C1/FFFFFF?text=Sakura',
        rarity: 'Limited',
        color: 'Light Pink',
        estimatedValue: { min: 55, max: 55 },
        originalPrice: 39.99,
        description: 'Icy blue winter',
    },

    // Mega Edition Series (1 figures: 1 common)
    {
        id: '89',
        name: 'Mega Labubu (40cm)',
        series: 'Mega Edition',
        releaseDate: '2024-12-20',
        dimensions: '40cm / 15.7 inches',
        image: 'https://via.placeholder.com/150/DDA0DD/FFFFFF?text=Fairy+Tale',
        rarity: 'Ultra-rare',
        color: 'Plum',
        estimatedValue: { min: 180, max: 180 },
        originalPrice: 99.99,
        description: 'Oversized exclusive',
    },

    // Tycoco Series (1 figures: 1 common)
    {
        id: '90',
        name: 'Tycoco Boyfriend',
        series: 'Tycoco',
        releaseDate: '2024-07-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=Found+You',
        rarity: 'Limited',
        color: 'Hot Pink',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99,
        description: 'Tycoco with boyfriend outfit',
    },

    // Collab Series (1 figures: 1 common)
    {
        id: '101',
        name: 'Vans Collab Labubu',
        series: 'Collab',
        releaseDate: '2024-08-20',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/87CEEB/FFFFFF?text=Starlight',
        rarity: 'Limited',
        color: 'Sky Blue',
        estimatedValue: { min: 120, max: 120 },
        originalPrice: 49.99,
        description: 'Vans sneaker collab',
    },

    // Fall in Wild Series (2 figures: 2 common)
    {
        id: '104',
        name: 'Fall in Wild Big Plush',
        series: 'Fall in Wild',
        releaseDate: '2024-05-01',
        dimensions: '30cm / 11.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Golden+Harvest',
        rarity: 'Limited',
        color: 'Gold',
        estimatedValue: { min: 60, max: 60 },
        originalPrice: 49.99,
        description: 'Large forest plush',
    },
    {
        id: '105',
        name: 'Fall in Wild Keychain',
        series: 'Fall in Wild',
        releaseDate: '2024-05-01',
        dimensions: '10cm / 3.9 inches',
        image: 'https://via.placeholder.com/150/87CEEB/FFFFFF?text=Frosty+Winter',
        rarity: 'Limited',
        color: 'Sky Blue',
        estimatedValue: { min: 25, max: 25 },
        originalPrice: 19.99,
        description: 'Mini forest keychain',
    }
];

// Get unique series for filter pills
export const SERIES_OPTIONS = ['All', ...new Set(LABUBU_DATA.map(l => l.series))];
