// Complete Labubu Dataset - All 113 Figures
export const LABUBU_DATA = [
    // Exciting Macaron Series (V1 Blind Box: 7 figures)
    {
        id: '1',
        name: 'Lychee Berry',
        series: 'Exciting Macaron',
        releaseDate: '2023-06-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=Lychee+Berry',
        rarity: 'Common',
        color: 'Pink',
        estimatedValue: { min: 15, max: 15 },
        originalPrice: 12.90
    },
    {
        id: '2',
        name: 'Sesame Bean',
        series: 'Exciting Macaron',
        releaseDate: '2023-06-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/696969/FFFFFF?text=Sesame+Bean',
        rarity: 'Common',
        color: 'Grey',
        estimatedValue: { min: 14.5, max: 14.5 },
        originalPrice: 12.90
    },
    {
        id: '3',
        name: 'Green Grape',
        series: 'Exciting Macaron',
        releaseDate: '2023-06-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/32CD32/FFFFFF?text=Green+Grape',
        rarity: 'Common',
        color: 'Green',
        estimatedValue: { min: 15.5, max: 15.5 },
        originalPrice: 12.90
    },
    {
        id: '4',
        name: 'Soy Milk',
        series: 'Exciting Macaron',
        releaseDate: '2023-06-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/F5F5DC/FFFFFF?text=Soy+Milk',
        rarity: 'Common',
        color: 'Cream',
        estimatedValue: { min: 14, max: 14 },
        originalPrice: 12.90
    },
    {
        id: '5',
        name: 'Sea Salt Coconut',
        series: 'Exciting Macaron',
        releaseDate: '2023-06-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/87CEEB/FFFFFF?text=Sea+Salt',
        rarity: 'Common',
        color: 'Blue',
        estimatedValue: { min: 16, max: 16 },
        originalPrice: 12.90
    },
    {
        id: '6',
        name: 'Toffee',
        series: 'Exciting Macaron',
        releaseDate: '2023-06-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/D2691E/FFFFFF?text=Toffee',
        rarity: 'Common',
        color: 'Brown',
        estimatedValue: { min: 15, max: 15 },
        originalPrice: 12.90
    },
    {
        id: '7',
        name: 'Chestnut Cocoa (Secret)',
        series: 'Exciting Macaron',
        releaseDate: '2023-06-01',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/8B4513/FFFFFF?text=Secret',
        rarity: 'Secret',
        color: 'Dark Brown',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 12.90
    },

    // Have a Seat Series (V2 Blind Box: 7 figures)
    {
        id: '8',
        name: 'Sisi',
        series: 'Have a Seat',
        releaseDate: '2023-09-15',
        dimensions: '8cm / 3.2 inches',
        image: 'https://via.placeholder.com/150/F5DEB3/FFFFFF?text=Sisi',
        rarity: 'Common',
        color: 'Light Beige',
        estimatedValue: { min: 16, max: 16 },
        originalPrice: 13.50
    },
    {
        id: '9',
        name: 'Hehe',
        series: 'Have a Seat',
        releaseDate: '2023-09-15',
        dimensions: '8cm / 3.2 inches',
        image: 'https://via.placeholder.com/150/808080/FFFFFF?text=Hehe',
        rarity: 'Common',
        color: 'Gray',
        estimatedValue: { min: 15.5, max: 15.5 },
        originalPrice: 13.50
    },
    {
        id: '10',
        name: 'Zizi',
        series: 'Have a Seat',
        releaseDate: '2023-09-15',
        dimensions: '8cm / 3.2 inches',
        image: 'https://via.placeholder.com/150/FFB6C1/FFFFFF?text=Zizi',
        rarity: 'Common',
        color: 'Pink',
        estimatedValue: { min: 15, max: 15 },
        originalPrice: 13.50
    },
    {
        id: '11',
        name: 'Baba',
        series: 'Have a Seat',
        releaseDate: '2023-09-15',
        dimensions: '8cm / 3.2 inches',
        image: 'https://via.placeholder.com/150/98FB98/FFFFFF?text=Baba',
        rarity: 'Common',
        color: 'Green',
        estimatedValue: { min: 14.5, max: 14.5 },
        originalPrice: 13.50
    },
    {
        id: '12',
        name: 'Ququ',
        series: 'Have a Seat',
        releaseDate: '2023-09-15',
        dimensions: '8cm / 3.2 inches',
        image: 'https://via.placeholder.com/150/00FF7F/FFFFFF?text=Ququ',
        rarity: 'Common',
        color: 'Mint Green',
        estimatedValue: { min: 16.5, max: 16.5 },
        originalPrice: 13.50
    },
    {
        id: '13',
        name: 'Dada',
        series: 'Have a Seat',
        releaseDate: '2023-09-15',
        dimensions: '8cm / 3.2 inches',
        image: 'https://via.placeholder.com/150/FFB6C1/FFFFFF?text=Dada',
        rarity: 'Common',
        color: 'Pale Pink',
        estimatedValue: { min: 15, max: 15 },
        originalPrice: 13.50
    },
    {
        id: '14',
        name: 'DuoDuo (Secret)',
        series: 'Have a Seat',
        releaseDate: '2023-09-15',
        dimensions: '8cm / 3.2 inches',
        image: 'https://via.placeholder.com/150/8B4513/FFFFFF?text=Secret',
        rarity: 'Secret',
        color: 'Chocolate Brown',
        estimatedValue: { min: 60, max: 60 },
        originalPrice: 13.50
    },

    // Big into Energy Series (V3 Blind Box: 7 figures)
    {
        id: '15',
        name: 'Hope Labubu',
        series: 'Big into Energy',
        releaseDate: '2024-01-10',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Hope',
        rarity: 'Common',
        color: 'Yellow',
        estimatedValue: { min: 16, max: 16 },
        originalPrice: 14.00
    },
    {
        id: '16',
        name: 'Power Surge Labubu',
        series: 'Big into Energy',
        releaseDate: '2024-01-10',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/FF4500/FFFFFF?text=Power',
        rarity: 'Common',
        color: 'Orange',
        estimatedValue: { min: 15.5, max: 15.5 },
        originalPrice: 14.00
    },
    {
        id: '17',
        name: 'Energy Burst Labubu',
        series: 'Big into Energy',
        releaseDate: '2024-01-10',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/00FF00/FFFFFF?text=Energy',
        rarity: 'Common',
        color: 'Green',
        estimatedValue: { min: 15, max: 15 },
        originalPrice: 14.00
    },
    {
        id: '18',
        name: 'Adrenaline Labubu',
        series: 'Big into Energy',
        releaseDate: '2024-01-10',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/FF0000/FFFFFF?text=Adrenaline',
        rarity: 'Common',
        color: 'Red',
        estimatedValue: { min: 16, max: 16 },
        originalPrice: 14.00
    },
    {
        id: '19',
        name: 'Boost Labubu',
        series: 'Big into Energy',
        releaseDate: '2024-01-10',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/0000FF/FFFFFF?text=Boost',
        rarity: 'Common',
        color: 'Blue',
        estimatedValue: { min: 15.5, max: 15.5 },
        originalPrice: 14.00
    },
    {
        id: '20',
        name: 'Charge Labubu',
        series: 'Big into Energy',
        releaseDate: '2024-01-10',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/800080/FFFFFF?text=Charge',
        rarity: 'Rare',
        color: 'Purple',
        estimatedValue: { min: 30, max: 30 },
        originalPrice: 14.00
    },
    {
        id: '21',
        name: 'Rock the Universe (Secret)',
        series: 'Big into Energy',
        releaseDate: '2024-01-10',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/FF1493/FFFFFF?text=Secret',
        rarity: 'Secret',
        color: 'Cosmic',
        estimatedValue: { min: 75, max: 75 },
        originalPrice: 14.00
    },

    // Pin for Love Series (V4 Mini Blind Box: 30 figures - 26 letters + 4 specials)
    {
        id: '22',
        name: 'A - Adventure',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=A',
        rarity: 'Common',
        color: 'Pink',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.50
    },
    {
        id: '23',
        name: 'B - Belief',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/32CD32/FFFFFF?text=B',
        rarity: 'Common',
        color: 'Green',
        estimatedValue: { min: 11.5, max: 11.5 },
        originalPrice: 10.50
    },
    {
        id: '24',
        name: 'C - Courage',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF4500/FFFFFF?text=C',
        rarity: 'Common',
        color: 'Orange',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.50
    },
    {
        id: '25',
        name: 'D - Dream',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/87CEEB/FFFFFF?text=D',
        rarity: 'Common',
        color: 'Sky Blue',
        estimatedValue: { min: 11.5, max: 11.5 },
        originalPrice: 10.50
    },
    {
        id: '26',
        name: 'E - Energy',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=E',
        rarity: 'Common',
        color: 'Yellow',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.50
    },
    {
        id: '27',
        name: 'F - Freedom',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/00FF00/FFFFFF?text=F',
        rarity: 'Common',
        color: 'Green',
        estimatedValue: { min: 11.5, max: 11.5 },
        originalPrice: 10.50
    },
    {
        id: '28',
        name: 'G - Grace',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FFB6C1/FFFFFF?text=G',
        rarity: 'Common',
        color: 'Pink',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.50
    },
    {
        id: '29',
        name: 'H - Hope',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=H',
        rarity: 'Common',
        color: 'Hot Pink',
        estimatedValue: { min: 11.5, max: 11.5 },
        originalPrice: 10.50
    },
    {
        id: '30',
        name: 'I - Inspire',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/800080/FFFFFF?text=I',
        rarity: 'Common',
        color: 'Purple',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.50
    },
    {
        id: '31',
        name: 'J - Joy',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=J',
        rarity: 'Common',
        color: 'Gold',
        estimatedValue: { min: 11.5, max: 11.5 },
        originalPrice: 10.50
    },
    {
        id: '32',
        name: 'K - Kindness',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/32CD32/FFFFFF?text=K',
        rarity: 'Common',
        color: 'Lime Green',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.50
    },
    {
        id: '33',
        name: 'L - Love',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF1493/FFFFFF?text=L',
        rarity: 'Common',
        color: 'Deep Pink',
        estimatedValue: { min: 11.5, max: 11.5 },
        originalPrice: 10.50
    },
    {
        id: '34',
        name: 'M - Magic',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/9370DB/FFFFFF?text=M',
        rarity: 'Common',
        color: 'Medium Purple',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.50
    },
    {
        id: '35',
        name: 'N - Noble',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/4169E1/FFFFFF?text=N',
        rarity: 'Common',
        color: 'Royal Blue',
        estimatedValue: { min: 11.5, max: 11.5 },
        originalPrice: 10.50
    },
    {
        id: '36',
        name: 'O - Optimism',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FFA500/FFFFFF?text=O',
        rarity: 'Common',
        color: 'Orange',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.50
    },
    {
        id: '37',
        name: 'P - Peace',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/00CED1/FFFFFF?text=P',
        rarity: 'Common',
        color: 'Dark Turquoise',
        estimatedValue: { min: 11.5, max: 11.5 },
        originalPrice: 10.50
    },
    {
        id: '38',
        name: 'Q - Quest',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/8B008B/FFFFFF?text=Q',
        rarity: 'Common',
        color: 'Dark Magenta',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.50
    },
    {
        id: '39',
        name: 'R - Rainbow',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=R',
        rarity: 'Common',
        color: 'Hot Pink',
        estimatedValue: { min: 11.5, max: 11.5 },
        originalPrice: 10.50
    },
    {
        id: '40',
        name: 'S - Smile',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=S',
        rarity: 'Common',
        color: 'Gold',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.50
    },
    {
        id: '41',
        name: 'T - Trust',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/32CD32/FFFFFF?text=T',
        rarity: 'Common',
        color: 'Lime Green',
        estimatedValue: { min: 11.5, max: 11.5 },
        originalPrice: 10.50
    },
    {
        id: '42',
        name: 'U - Unity',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/0000FF/FFFFFF?text=U',
        rarity: 'Common',
        color: 'Blue',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.50
    },
    {
        id: '43',
        name: 'V - Victory',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF0000/FFFFFF?text=V',
        rarity: 'Common',
        color: 'Red',
        estimatedValue: { min: 11.5, max: 11.5 },
        originalPrice: 10.50
    },
    {
        id: '44',
        name: 'W - Wisdom',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/800080/FFFFFF?text=W',
        rarity: 'Common',
        color: 'Purple',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.50
    },
    {
        id: '45',
        name: 'X - Xtra',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF4500/FFFFFF?text=X',
        rarity: 'Common',
        color: 'Orange Red',
        estimatedValue: { min: 11.5, max: 11.5 },
        originalPrice: 10.50
    },
    {
        id: '46',
        name: 'Y - Youth',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FFFF00/FFFFFF?text=Y',
        rarity: 'Common',
        color: 'Yellow',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.50
    },
    {
        id: '47',
        name: 'Z - Zeal',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/9370DB/FFFFFF?text=Z',
        rarity: 'Common',
        color: 'Medium Purple',
        estimatedValue: { min: 12, max: 12 },
        originalPrice: 10.50
    },
    {
        id: '48',
        name: '? - Emm',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/800080/FFFFFF?text=?',
        rarity: 'Common',
        color: 'Purple',
        estimatedValue: { min: 13, max: 13 },
        originalPrice: 10.50
    },
    {
        id: '49',
        name: '&',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=&',
        rarity: 'Common',
        color: 'Hot Pink',
        estimatedValue: { min: 12.5, max: 12.5 },
        originalPrice: 10.50
    },
    {
        id: '50',
        name: 'Heart (Secret)',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FF1493/FFFFFF?text=Heart',
        rarity: 'Secret',
        color: 'Deep Pink',
        estimatedValue: { min: 40, max: 40 },
        originalPrice: 10.50
    },
    {
        id: '51',
        name: '!',
        series: 'Pin for Love',
        releaseDate: '2024-03-01',
        dimensions: '5cm / 2 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=!',
        rarity: 'Secret',
        color: 'Gold',
        estimatedValue: { min: 45, max: 45 },
        originalPrice: 10.50
    },

    // Coca-Cola Collab (Blind Box: 11 figures)
    {
        id: '52',
        name: 'Classic Coke Labubu',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/C0C0C0/FFFFFF?text=Coke',
        rarity: 'Common',
        color: 'Silver',
        estimatedValue: { min: 18, max: 18 },
        originalPrice: 15.00
    },
    {
        id: '53',
        name: 'Coke Bottle Labubu',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/8B4513/FFFFFF?text=Bottle',
        rarity: 'Common',
        color: 'Brown',
        estimatedValue: { min: 17.5, max: 17.5 },
        originalPrice: 15.00
    },
    {
        id: '54',
        name: 'Cherry Coke Labubu',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/FF0000/FFFFFF?text=Cherry',
        rarity: 'Common',
        color: 'Red',
        estimatedValue: { min: 18.5, max: 18.5 },
        originalPrice: 15.00
    },
    {
        id: '55',
        name: 'Diet Coke Labubu',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/708090/FFFFFF?text=Diet',
        rarity: 'Common',
        color: 'Slate Gray',
        estimatedValue: { min: 17, max: 17 },
        originalPrice: 15.00
    },
    {
        id: '56',
        name: 'Coke Zero Labubu',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/000000/FFFFFF?text=Zero',
        rarity: 'Common',
        color: 'Black',
        estimatedValue: { min: 17.5, max: 17.5 },
        originalPrice: 15.00
    },
    {
        id: '57',
        name: 'Vanilla Coke Labubu',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/F5DEB3/FFFFFF?text=Vanilla',
        rarity: 'Common',
        color: 'Wheat',
        estimatedValue: { min: 18, max: 18 },
        originalPrice: 15.00
    },
    {
        id: '58',
        name: 'Surfboard Coke Labubu',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/87CEEB/FFFFFF?text=Surf',
        rarity: 'Common',
        color: 'Sky Blue',
        estimatedValue: { min: 19, max: 19 },
        originalPrice: 15.00
    },
    {
        id: '59',
        name: 'Festive Coke Labubu',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Festive',
        rarity: 'Common',
        color: 'Gold',
        estimatedValue: { min: 18.5, max: 18.5 },
        originalPrice: 15.00
    },
    {
        id: '60',
        name: 'Silver Can Labubu',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/C0C0C0/FFFFFF?text=Silver',
        rarity: 'Rare',
        color: 'Silver',
        estimatedValue: { min: 35, max: 35 },
        originalPrice: 15.00
    },
    {
        id: '61',
        name: 'Coke Secret Variant',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/8B0000/FFFFFF?text=Secret',
        rarity: 'Secret',
        color: 'Dark Red',
        estimatedValue: { min: 70, max: 70 },
        originalPrice: 15.00
    },
    {
        id: '62',
        name: 'Holiday Coke Labubu',
        series: 'Coca-Cola',
        releaseDate: '2024-07-20',
        dimensions: '7.5cm / 3 inches',
        image: 'https://via.placeholder.com/150/FF0000/FFFFFF?text=Holiday',
        rarity: 'Common',
        color: 'Red',
        estimatedValue: { min: 18, max: 18 },
        originalPrice: 15.00
    },

    // Fall in Wild Series and Other Plush (distinct releases)
    {
        id: '63',
        name: 'Fall in Wild - Big Plush',
        series: 'Fall in Wild',
        releaseDate: '2024-05-01',
        dimensions: '30cm / 11.8 inches',
        image: 'https://via.placeholder.com/150/228B22/FFFFFF?text=Big+Wild',
        rarity: 'Limited',
        color: 'Forest Green',
        estimatedValue: { min: 60, max: 60 },
        originalPrice: 49.99
    },
    {
        id: '64',
        name: 'Fall in Wild - Keychain Pendant',
        series: 'Fall in Wild',
        releaseDate: '2024-05-01',
        dimensions: '10cm / 3.9 inches',
        image: 'https://via.placeholder.com/150/32CD32/FFFFFF?text=Wild+Key',
        rarity: 'Limited',
        color: 'Lime Green',
        estimatedValue: { min: 25, max: 25 },
        originalPrice: 19.99
    },
    {
        id: '65',
        name: 'Time to Chill Labubu',
        series: 'Other Plush',
        releaseDate: '2024-02-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/87CEEB/FFFFFF?text=Chill',
        rarity: 'Limited',
        color: 'Sky Blue',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99
    },
    {
        id: '66',
        name: 'Jump for Joy Labubu',
        series: 'Other Plush',
        releaseDate: '2024-04-10',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Joy',
        rarity: 'Limited',
        color: 'Gold',
        estimatedValue: { min: 45, max: 45 },
        originalPrice: 39.99
    },
    {
        id: '67',
        name: 'Dress Be Latte Labubu',
        series: 'Other Plush',
        releaseDate: '2024-06-20',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/D2691E/FFFFFF?text=Latte',
        rarity: 'Limited',
        color: 'Chocolate',
        estimatedValue: { min: 48, max: 48 },
        originalPrice: 39.99
    },
    {
        id: '68',
        name: 'Flip with Me Labubu',
        series: 'Other Plush',
        releaseDate: '2024-08-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=Flip',
        rarity: 'Limited',
        color: 'Hot Pink',
        estimatedValue: { min: 47, max: 47 },
        originalPrice: 39.99
    },
    {
        id: '69',
        name: 'Let\'s Checkmate - Big',
        series: 'Other Plush',
        releaseDate: '2024-09-10',
        dimensions: '30cm / 11.8 inches',
        image: 'https://via.placeholder.com/150/696969/FFFFFF?text=Chess+Big',
        rarity: 'Limited',
        color: 'Dim Gray',
        estimatedValue: { min: 60, max: 60 },
        originalPrice: 49.99
    },
    {
        id: '70',
        name: 'Let\'s Checkmate - Hangcard',
        series: 'Other Plush',
        releaseDate: '2024-09-10',
        dimensions: '10cm / 3.9 inches',
        image: 'https://via.placeholder.com/150/808080/FFFFFF?text=Chess+Key',
        rarity: 'Limited',
        color: 'Gray',
        estimatedValue: { min: 25, max: 25 },
        originalPrice: 19.99
    },
    {
        id: '71',
        name: 'Walk By Fortune Labubu',
        series: 'Other Plush',
        releaseDate: '2024-10-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Fortune',
        rarity: 'Limited',
        color: 'Gold',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99
    },
    {
        id: '72',
        name: 'Best of Luck Labubu',
        series: 'Other Plush',
        releaseDate: '2024-10-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/32CD32/FFFFFF?text=Luck',
        rarity: 'Limited',
        color: 'Lime Green',
        estimatedValue: { min: 48, max: 48 },
        originalPrice: 39.99
    },
    {
        id: '73',
        name: 'Catch Me If You Like Me Labubu',
        series: 'Other Plush',
        releaseDate: '2024-07-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FF1493/FFFFFF?text=Catch+Me',
        rarity: 'Limited',
        color: 'Deep Pink',
        estimatedValue: { min: 45, max: 45 },
        originalPrice: 39.99
    },
    {
        id: '74',
        name: 'Labubu Vans',
        series: 'Other Plush',
        releaseDate: '2024-08-20',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/000000/FFFFFF?text=Vans',
        rarity: 'Limited',
        color: 'Black',
        estimatedValue: { min: 65, max: 65 },
        originalPrice: 49.99
    },
    {
        id: '75',
        name: 'Halloween Sitting Pumpkin Labubu',
        series: 'Other Plush',
        releaseDate: '2024-10-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FF8C00/FFFFFF?text=Pumpkin',
        rarity: 'Limited',
        color: 'Dark Orange',
        estimatedValue: { min: 55, max: 55 },
        originalPrice: 39.99
    },
    {
        id: '76',
        name: 'Be Fancy Now Labubu',
        series: 'Other Plush',
        releaseDate: '2024-11-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/9370DB/FFFFFF?text=Fancy',
        rarity: 'Limited',
        color: 'Medium Purple',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99
    },
    {
        id: '77',
        name: 'Wings of Fantasy Labubu',
        series: 'Other Plush',
        releaseDate: '2024-12-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/DDA0DD/FFFFFF?text=Fantasy',
        rarity: 'Limited',
        color: 'Plum',
        estimatedValue: { min: 52, max: 52 },
        originalPrice: 39.99
    },
    {
        id: '78',
        name: 'Wings of Fortune Labubu',
        series: 'Other Plush',
        releaseDate: '2024-12-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Fortune+Wings',
        rarity: 'Limited',
        color: 'Gold',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99
    },
    {
        id: '79',
        name: 'Hide and Seek Labubu',
        series: 'Other Plush',
        releaseDate: '2024-06-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=Hide+Seek',
        rarity: 'Limited',
        color: 'Hot Pink',
        estimatedValue: { min: 60, max: 60 },
        originalPrice: 45.00
    },
    {
        id: '80',
        name: 'Good Lucky Labubu',
        series: 'Other Plush',
        releaseDate: '2024-06-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Good+Lucky',
        rarity: 'Limited',
        color: 'Gold',
        estimatedValue: { min: 58, max: 58 },
        originalPrice: 45.00
    },
    {
        id: '81',
        name: 'Rock the Universe Labubu',
        series: 'Other Plush',
        releaseDate: '2024-11-15',
        dimensions: '30cm / 11.8 inches',
        image: 'https://via.placeholder.com/150/4B0082/FFFFFF?text=Universe',
        rarity: 'Limited',
        color: 'Indigo',
        estimatedValue: { min: 65, max: 65 },
        originalPrice: 49.99
    },
    {
        id: '82',
        name: '14th Anniversary Labubu',
        series: 'Other Plush',
        releaseDate: '2024-12-10',
        dimensions: '30cm / 11.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Anniversary',
        rarity: 'Limited',
        color: 'Gold',
        estimatedValue: { min: 80, max: 80 },
        originalPrice: 59.99
    },

    // Mokoko Variants (7 figures)
    {
        id: '83',
        name: 'Close to Sweet - Big',
        series: 'Mokoko',
        releaseDate: '2024-03-15',
        dimensions: '30cm / 11.8 inches',
        image: 'https://via.placeholder.com/150/FFB6C1/FFFFFF?text=Sweet+Big',
        rarity: 'Limited',
        color: 'Light Pink',
        estimatedValue: { min: 60, max: 60 },
        originalPrice: 49.99
    },
    {
        id: '84',
        name: 'Close to Sweet - Keychain',
        series: 'Mokoko',
        releaseDate: '2024-03-15',
        dimensions: '10cm / 3.9 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=Sweet+Key',
        rarity: 'Limited',
        color: 'Hot Pink',
        estimatedValue: { min: 25, max: 25 },
        originalPrice: 19.99
    },
    {
        id: '85',
        name: 'Fall into Spring - Big',
        series: 'Mokoko',
        releaseDate: '2024-04-01',
        dimensions: '30cm / 11.8 inches',
        image: 'https://via.placeholder.com/150/98FB98/FFFFFF?text=Spring+Big',
        rarity: 'Limited',
        color: 'Pale Green',
        estimatedValue: { min: 58, max: 58 },
        originalPrice: 49.99
    },
    {
        id: '86',
        name: 'Fall into Spring - Keychain',
        series: 'Mokoko',
        releaseDate: '2024-04-01',
        dimensions: '10cm / 3.9 inches',
        image: 'https://via.placeholder.com/150/32CD32/FFFFFF?text=Spring+Key',
        rarity: 'Limited',
        color: 'Lime Green',
        estimatedValue: { min: 24, max: 24 },
        originalPrice: 19.99
    },
    {
        id: '87',
        name: 'The Blue Diamond',
        series: 'Mokoko',
        releaseDate: '2024-05-10',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/4169E1/FFFFFF?text=Diamond',
        rarity: 'Limited',
        color: 'Royal Blue',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99
    },
    {
        id: '88',
        name: 'Magic of Pumpkin',
        series: 'Mokoko',
        releaseDate: '2024-10-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FF8C00/FFFFFF?text=Magic+Pumpkin',
        rarity: 'Limited',
        color: 'Dark Orange',
        estimatedValue: { min: 55, max: 55 },
        originalPrice: 39.99
    },
    {
        id: '89',
        name: 'Twinkly Fairy Tale',
        series: 'Mokoko',
        releaseDate: '2024-12-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/DDA0DD/FFFFFF?text=Fairy+Tale',
        rarity: 'Limited',
        color: 'Plum',
        estimatedValue: { min: 52, max: 52 },
        originalPrice: 39.99
    },

    // Zimomo Variants (2 figures)
    {
        id: '90',
        name: 'I Found You Zimomo',
        series: 'Zimomo',
        releaseDate: '2024-06-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=Found+You',
        rarity: 'Limited',
        color: 'Hot Pink',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99
    },
    {
        id: '91',
        name: 'Angel in Clouds Zimomo',
        series: 'Zimomo',
        releaseDate: '2024-06-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/87CEEB/FFFFFF?text=Angel+Clouds',
        rarity: 'Rare',
        color: 'Sky Blue',
        estimatedValue: { min: 60, max: 60 },
        originalPrice: 39.99
    },

    // Additional Figures to Reach 113 (Tycoco, regional, themed uniques)
    {
        id: '92',
        name: 'Tycoco Boyfriend Variant',
        series: 'Tycoco',
        releaseDate: '2024-07-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFB6C1/FFFFFF?text=Boyfriend',
        rarity: 'Limited',
        color: 'Light Pink',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99
    },
    {
        id: '93',
        name: 'Forest Fairy Tale Labubu',
        series: 'Other Plush',
        releaseDate: '2024-08-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/228B22/FFFFFF?text=Forest+Fairy',
        rarity: 'Limited',
        color: 'Forest Green',
        estimatedValue: { min: 48, max: 48 },
        originalPrice: 39.99
    },
    {
        id: '94',
        name: 'Wacky Mart Labubu',
        series: 'Other Plush',
        releaseDate: '2024-09-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Wacky+Mart',
        rarity: 'Limited',
        color: 'Gold',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99
    },
    {
        id: '95',
        name: 'Space Adventure Labubu',
        series: 'Other Plush',
        releaseDate: '2024-10-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/4169E1/FFFFFF?text=Space+Adventure',
        rarity: 'Limited',
        color: 'Royal Blue',
        estimatedValue: { min: 52, max: 52 },
        originalPrice: 39.99
    },
    {
        id: '96',
        name: 'Playing Games Labubu',
        series: 'Other Plush',
        releaseDate: '2024-11-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/9370DB/FFFFFF?text=Playing+Games',
        rarity: 'Limited',
        color: 'Medium Purple',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99
    },
    {
        id: '97',
        name: 'Winter Snowflake Labubu',
        series: 'Other Plush',
        releaseDate: '2024-12-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/F0F8FF/FFFFFF?text=Snowflake',
        rarity: 'Limited',
        color: 'Alice Blue',
        estimatedValue: { min: 55, max: 55 },
        originalPrice: 39.99
    },
    {
        id: '98',
        name: 'Sakura Blossom Labubu',
        series: 'Other Plush',
        releaseDate: '2024-03-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFB6C1/FFFFFF?text=Sakura',
        rarity: 'Limited',
        color: 'Light Pink',
        estimatedValue: { min: 60, max: 60 },
        originalPrice: 45.00
    },
    {
        id: '99',
        name: 'Lunar New Year Labubu',
        series: 'Other Plush',
        releaseDate: '2024-02-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Lunar+New+Year',
        rarity: 'Limited',
        color: 'Gold',
        estimatedValue: { min: 58, max: 58 },
        originalPrice: 45.00
    },
    {
        id: '100',
        name: 'Mermaid Labubu',
        series: 'Other Plush',
        releaseDate: '2024-07-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/00CED1/FFFFFF?text=Mermaid',
        rarity: 'Limited',
        color: 'Dark Turquoise',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99
    },
    {
        id: '101',
        name: 'Starlight Labubu',
        series: 'Other Plush',
        releaseDate: '2024-08-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/87CEEB/FFFFFF?text=Starlight',
        rarity: 'Limited',
        color: 'Sky Blue',
        estimatedValue: { min: 48, max: 48 },
        originalPrice: 39.99
    },
    {
        id: '102',
        name: 'Rainbow Dream Labubu',
        series: 'Other Plush',
        releaseDate: '2024-09-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=Rainbow+Dream',
        rarity: 'Limited',
        color: 'Hot Pink',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99
    },
    {
        id: '103',
        name: 'Candy Carnival Labubu',
        series: 'Other Plush',
        releaseDate: '2024-10-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Candy+Carnival',
        rarity: 'Limited',
        color: 'Gold',
        estimatedValue: { min: 52, max: 52 },
        originalPrice: 39.99
    },
    {
        id: '104',
        name: 'Golden Harvest Labubu',
        series: 'Other Plush',
        releaseDate: '2024-11-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Golden+Harvest',
        rarity: 'Limited',
        color: 'Gold',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99
    },
    {
        id: '105',
        name: 'Frosty Winter Labubu',
        series: 'Other Plush',
        releaseDate: '2024-12-01',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/87CEEB/FFFFFF?text=Frosty+Winter',
        rarity: 'Limited',
        color: 'Sky Blue',
        estimatedValue: { min: 55, max: 55 },
        originalPrice: 39.99
    },
    {
        id: '106',
        name: 'Cosmic Explorer Labubu',
        series: 'Other Plush',
        releaseDate: '2024-10-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/4B0082/FFFFFF?text=Cosmic+Explorer',
        rarity: 'Limited',
        color: 'Indigo',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99
    },
    {
        id: '107',
        name: 'Dreamy Cloud Labubu',
        series: 'Other Plush',
        releaseDate: '2024-11-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/F0F8FF/FFFFFF?text=Dreamy+Cloud',
        rarity: 'Limited',
        color: 'Alice Blue',
        estimatedValue: { min: 48, max: 48 },
        originalPrice: 39.99
    },
    {
        id: '108',
        name: 'Festival Fireworks Labubu',
        series: 'Other Plush',
        releaseDate: '2024-12-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/FF4500/FFFFFF?text=Festival+Fireworks',
        rarity: 'Limited',
        color: 'Orange Red',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99
    },
    {
        id: '109',
        name: 'Tropical Paradise Labubu',
        series: 'Other Plush',
        releaseDate: '2024-07-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/32CD32/FFFFFF?text=Tropical+Paradise',
        rarity: 'Limited',
        color: 'Lime Green',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99
    },
    {
        id: '110',
        name: 'Moonlit Garden Labubu',
        series: 'Other Plush',
        releaseDate: '2024-08-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/9370DB/FFFFFF?text=Moonlit+Garden',
        rarity: 'Limited',
        color: 'Medium Purple',
        estimatedValue: { min: 48, max: 48 },
        originalPrice: 39.99
    },
    {
        id: '111',
        name: 'Starry Adventure Labubu',
        series: 'Other Plush',
        releaseDate: '2024-09-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/87CEEB/FFFFFF?text=Starry+Adventure',
        rarity: 'Limited',
        color: 'Sky Blue',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99
    },
    {
        id: '112',
        name: 'Lucky Clover Labubu',
        series: 'Other Plush',
        releaseDate: '2024-10-15',
        dimensions: '25cm / 9.8 inches',
        image: 'https://via.placeholder.com/150/32CD32/FFFFFF?text=Lucky+Clover',
        rarity: 'Limited',
        color: 'Lime Green',
        estimatedValue: { min: 50, max: 50 },
        originalPrice: 39.99
    },
    {
        id: '113',
        name: 'Mega Edition Labubu Variant',
        series: 'Other Plush',
        releaseDate: '2024-12-20',
        dimensions: '40cm / 15.7 inches',
        image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Mega+Edition',
        rarity: 'Ultra Rare',
        color: 'Gold',
        estimatedValue: { min: 150, max: 150 },
        originalPrice: 99.99
    }
];

// Get unique series for filter pills
export const SERIES_OPTIONS = ['All', ...new Set(LABUBU_DATA.map(l => l.series))];